name: ansible
services:
  controller:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: benoitbe/ansible-controller
    command: "${cmd:-tail -f /dev/null}"
    stdin_open: true
    tty: true
    env_file:
      - docker/nodes.env
    group_add:
      - root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - public_ssh_key:/usr/local/share/.ssh
    develop:
      watch:
        - action: sync
          path: .
          target: /usr/local/ansible
          ignore:
            - docker/

volumes:
  public_ssh_key:
  ansible_nodes_dockerfiles:

configs:
  docker_socket:
    file: /var/run/docker.sock
