version: "3.8"
services:
  ansible:
    build: control-node
    image: benoitbe/ansible-control-node
    container_name: ansible
    volumes: 
      - ./control-node:/usr/local/ansible
      - ansible_playground_ssh_keys:/root/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: tail -f /dev/null
    
volumes:
  ansible_playground_ssh_keys:
    name: ansible_playground_ssh_keys

networks:
  default:
    name: ansible_playground