- hosts: localhost
  gather_facts: false

  vars:
    distributions:
      - alpine
      - debian
      - ubuntu

    package_managers:
      alpine: apk add --no-cache
      debian: &apt |-
        apt-get -qq update \
        && apt-get -qq install --yes --no-install-recommends
      ubuntu: *apt

  tasks:
    - template:
        src: node.Dockerfile.j2
        dest: "templates/{{ item }}.Dockerfile"
      loop: "{{ distributions }}"

    - community.docker.docker_image:
        source: build
        name: benoitbe/ansible-node
        tag: "{{ item }}"
        build:
          path: /var/empty
          dockerfile: "/usr/local/bin/templates/{{ item }}.Dockerfile"
      loop: "{{ distributions }}"

    - community.docker.docker_container:
        name: "node-{{ item }}-{{ '1' }}"
        image: "benoitbe/ansible-node:{{ item }}"
        networks:
          - name: ansible_default
        volumes:
          - ansible_public_ssh_key:/usr/local/share/.ssh
      loop: "{{ distributions }}"
      # loop_control:
      #   extended: true

# TODO:
# 1. be able to have multiple container of a distribution (node-alpine-1, node-alpine-2, etc)
# 2. pass all nodes_* variables from make to the container
# 3. keep on investigating docker compose watch
# 4. add distributions (one that uses pacman, arch?, one that uses yum, one that uses dnf)