- hosts: localhost
  gather_facts: false

  vars:
    package_managers:
      alpine: apk add --no-cache
      debian: &apt |-
        apt-get -qq update \
        && apt-get -qq install --yes --no-install-recommends
      ubuntu: *apt

  tasks:
    - set_fact:
        nodes: >-
          {{
            nodes | default([]) + (
              [item.0] | product(range(1, (item.1 | int) + 1)) | map('join', '-')
            )
          }}
      loop: >-
        {{
          package_managers.keys()
            | zip(query('env', *['nodes_'] | product(package_managers.keys()) | map('join')))
            | selectattr(1)
        }}

    - ansible.builtin.template:
        src: node.Dockerfile.j2
        dest: "/var/tmp/{{ item }}.Dockerfile"
      loop: "{{ nodes | map('split', '-') | map(attribute=0) | unique }}"

    - community.docker.docker_image:
        source: build
        name: benoitbe/ansible-node
        tag: "{{ item }}"
        build:
          path: /var/empty
          dockerfile: "/var/tmp/{{ item }}.Dockerfile"
      loop: "{{ nodes | map('split', '-') | map(attribute=0) | unique }}"

    - community.docker.docker_container:
        name: "node-{{ item }}"
        image: "benoitbe/ansible-node:{{ (item | split('-')).0 }}"
        labels:
          com.docker.compose.config-hash: ''
          com.docker.compose.project: ansible
          com.docker.compose.service: node
        networks:
          - name: ansible_default
        volumes:
          - ansible_public_ssh_key:/usr/local/share/.ssh:nocopy
      loop: "{{ nodes }}"
