- hosts: localhost
  gather_facts: no

  tasks:
    - ansible.builtin.pip:
        name:
          - docker-compose>=1.7.0,< 2.0.0

    - ansible.builtin.set_fact:
        containers: >-
          {{
            containers
              | default({})
              | combine({item: managed_node})
            }}
      loop: >-
        {{
          (nodes | default('node1,node2,node3')).split(',')
        }}
      vars:
        managed_node:
          build: "{{ playbook_dir }}"
          container_name: "{{ item }}"
          image: benoitbe/ansible-managed-node
          volumes:
            - ansible_playground_ssh_keys:/etc/ssh

    - community.docker.docker_compose:
        project_name: ansible
        definition: >-
          {{
            definition
              | combine({'services': containers})
          }}
      vars:
        definition:
          version: '3.9'
          volumes:
            ansible_playground_ssh_keys:
              external:
                name: ansible_playground_ssh_keys
          networks:
            default:
              external:
                name: ansible_playground