name: ansible
services:
  controller:
    build: .
    image: benoitbe/ansible-controller
    command: "${cmd:-ansible-playbook play.yml}"
    stdin_open: true
    tty: true
    env_file:
      - nodes.env
    volumes:
      - ..:/usr/local/ansible
      - /var/run/docker.sock:/var/run/docker.sock
      - public_ssh_key:/usr/local/share/.ssh

volumes:
  public_ssh_key:
  ansible_nodes_dockerfiles:
