name: "ansible"
services:
  controller:
    build: .
    image: benoitbe/ansible-controller
    command: "${cmd:-ansible-playbook play.yml}"
    stdin_open: true
    tty: true
    environment:
      ALPINE: "${NODES:-0}"
      DEBIAN: "${DEBIAN_NODES:-0}"
      UBUNTU: "${UBUNTU_NODES:-0}"
    volumes:
      - ..:/usr/local/ansible
      - ./bin/nodes.yml:/usr/local/bin/nodes.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - public_ssh_key:/usr/local/share/.ssh

volumes:
  public_ssh_key:
  ansible_nodes_dockerfiles:
