services:
  node-debian:
    build: node/debian
    image: benoitbe/ansible-node-debian
    deploy:
      mode: replicated
      replicas: "${debian:-1}"
    volumes:
      - public_ssh_key:/usr/local/share/.ssh

  controller:
    depends_on:
      - node-debian
