name: 'ansible'
services:
  controller:
    build: controller
    image: benoitbe/ansible-controller
    command: "${cmd:-ansible-playbook play.yml}"
    stdin_open: true
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/usr/local/ansible
      - ../conf/ansible.cfg:/etc/ansible/ansible.cfg
      - public_ssh_key:/usr/local/share/.ssh

volumes:
  public_ssh_key:
