version: "3.9"
name: ansible
services:
  ansible_controller:
    build: control-node
    image: benoitbe/ansible-control-node
    container_name: ansible_controller
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ansible_playground_ssh_keys:/root/.ssh
      - ../:/usr/local/ansible
      - ../conf/ansible.cfg:/etc/ansible/ansible.cfg

volumes:
  ansible_playground_ssh_keys:
    name: ansible_playground_ssh_keys

networks:
  default:
    name: ansible_playground