version: "3.9"
name: ansible
services:
  controller:
    build: controller
    image: benoitbe/ansible-controller
    command: "${cmd:-ansible-playbook play.yml}"
    container_name: ansible-controller
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../:/usr/local/ansible
      - ../conf/ansible.cfg:/etc/ansible/ansible.cfg
      - public_ssh_key:/usr/local/share/.ssh
  node:
    build: node/alpine
    image: benoitbe/ansible-node
    volumes:
      - public_ssh_key:/usr/local/share/.ssh
    deploy:
      mode: replicated
      replicas: "${nodes:-0}"
    depends_on:
      - controller
  node-debian:
    build: node/debian
    image: benoitbe/ansible-node-debian
    volumes:
      - public_ssh_key:/usr/local/share/.ssh
    deploy:
      mode: replicated
      replicas: "${nodes_debian:-0}"
    depends_on:
      - controller

volumes:
  public_ssh_key:
